---
title: "Openscapes JupyterHub Usage Reports"
---

We generate monthly reports of usage and costs of AWS resources in the 
NASA-Openscapes and NMFS-Openscapes JupyterHubs.

The report is generated automatically on the first day of every month using a 
GitHub Actions [workflow](https://github.com/Openscapes/openscapes.cloud/blob/main/.github/workflows/create-usage-report.yml), summarizing 
usage for the preceding month. The report can also be created on demand by 
triggering the workflow manually, by visiting the 
["Render and Save PDF" workflow page](https://github.com/openscapes/openscapes.cloud/actions/workflows/create-usage-report.yml), 
and clicking the "Run Workflow" button in the upper right corner.

Reports are stored in the [reports](_cost-reporting/reports/) directory.

## Monthly NASA reports

- [Usage report for 2024-07](_cost-reporting/reports/aws-usage-report_2024-07.pdf)
- [Usage report for 2024-08](_cost-reporting/reports/aws-usage-report_2024-08.pdf)
- [Usage report for 2024-09](_cost-reporting/reports/aws-usage-report_2024-09.pdf)
- [Usage report for 2024-10](_cost-reporting/reports/aws-usage-report_2024-10.pdf)
- [Usage report for 2024-11](_cost-reporting/reports/aws-usage-report_2024-11.pdf)
- [Usage report for 2024-12](_cost-reporting/reports/aws-usage-report_2024-12.pdf)
- [Usage report for 2025-01](_cost-reporting/reports/aws-usage-report_2025-01.pdf)
